version: "3.8"

services:
  database:
    container_name: go-rest-api-template-db
    image: postgres:15.3
    restart: on-failure
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready" ,"-U", "postgres", "-h", "127.0.0.1", "-p", "5432" ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - $HOME/docker/volumes/go-rest-api-template-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    container_name: go-rest-api-template
    build: .
    restart: always
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "3008:3008"
