version: "3.9"

services:
  postgresql:
    container_name: tama-db
    env_file:
      - dev.env
    image: postgres:15.3
    restart: on-failure
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready" ,"-U", "postgres", "-h", "127.0.0.1", "-p", "5432" ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - $HOME/docker/volumes/tama-postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    container_name: tama-server
    env_file:
      - dev.env
    build: .
    restart: always
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - "3008:3008"
